### ISSUE TITLE
Ost-West Ausrichtung Forecast

### ISSUE THREAD

**Issue by bscheufele** [solectrus/forecast-collector#151]
lässt sich für den Forecast auch eine Ost-West-Anlage konfigurieren?

**Comment by ledermann** [comment]
Du meinst eine Anlage mit mehreren, unterschiedlich ausgerichteten Dachseiten? Das wird derzeitig leider nicht unterstützt, es wird die Vorhersage nur für eine Dachrichtung ermittelt.

Das Thema gab es aber schon mal, siehe #64, dort wird auch eine Lösung von einem anderen User bereitgestellt.
