### ISSUE TITLE
Forecast wird nicht angezeigt.

### ISSUE THREAD

**Issue by GerhardPg** [solectrus/forecast-collector#274]
Hallo Georg,
ich habe das Problem, dass der Forecast nicht mehr angezeigt wird. Da ich in der Systemumgebung meines Synology-Nas doch eher unbedarft bin, war es für mich ein Erfolgserlebnis, im Container Manager (Docker) überhaupt an das Protokoll des solectrus-forecast-collectors-1 zu kommen. Ich habe mal die Meldungen, die seit dem letzten Start des des Dockers im Protokoll zu finden waren, in einem CSV-File angehängt. Ich hoffe, dass das die Fehlersuche eingrenzt.

Viele Grüße
Gerhard
[solectrus-forecast-collector-1.csv](https://github.com/solectrus/solectrus/files/14013991/solectrus-forecast-collector-1.csv)

**Comment by ledermann** [comment]
Die relevante Fehlermeldung dürfte diese hier sein:

```
/forecast-collector/app/config.rb:65:in `fetch': key not found: "FORECAST_INTERVAL" (KeyError)
```

Offenbar hat der Container keinen Zugriff auf die `.env`-Datei oder dort fehlt der Eintrag für `FORECAST_INTERVAL`. 

Hast du denn etwas an deiner Installation geändert? Laufen die anderen Komponenten? Finden sich Fehlermeldungen in den Logs der anderen Container?

**Comment by GerhardPg** [comment]
Ich bin mir nicht bewusst, etwas geändert zu haben. Die .env-Datei enthält den Eintrag FORECAST_INTERVAL=900
Die Logs der anderen Container enthalten keine Fehler.
Bei den Berechtigungen sehe ich ich auch keine Abweichungen bei der .env-Datei zu den anderen Files.

**Comment by ledermann** [comment]
Könntest Du die `.env` und `docker-compose.yml` hier posten?

**Comment by GerhardPg** [comment]
[solectrus.zip](https://github.com/solectrus/forecast-collector/files/14051258/solectrus.zip)

**Comment by ledermann** [comment]
@GerhardPg Ok, die Konfiguration habe ich mir angesehen. Fehler kann ich keine entdecken, hier bei mir lokal funktionieren deine Dateien tadellos - mit den jeweils neues Versionen der Docker-Images und leerer Datenbank.

Ich schlage vor, alle Container zu beenden, dann alle Images zu aktualisieren und dann neu starten, also so, von der Kommandozeile aus (SSH-Login):

```bash
docker-compose down
docker-compose pull
docker-compose up -d
```

Wenn das immer noch nicht zum Ziel führen sollte, poste bitte den gesamten Log-Output der obigen Kommandos. 

Ich vermute einen Zusammenhang mit dem Synology-Container-Manager. Ich würde empfehlen, nach Möglichkeit diesen **nicht** zu benutzen und von der Shell aus zu arbeiten. Soweit ich weiß, unterstützt der Container-Manager keine `.env`-Dateien.

**Comment by ledermann** [comment]
Ich vermute, du hast etwas Durcheinander mit den ENV-Variablen. Der App-Container muss das Passwort der PostgreSQL-Datenbank kennen. Das Passwort wird in der Variablen `POSTGRES_PASSWORD` festgelegt und an beide Container (App + Datenbank) durchgereicht. Das Datenbank-Passwort darf auch **nicht** im Nachhinein geändert werden!

Offenbar gibt es hier aber nun eine Abweichung. In deiner heute hier bereit gestellten `.env` war die Variable durch `*********` ersetzt worden. Das könnte die Ursache sein. Sorge dafür, dass vor dem Start aller Container die Variable `POSTGRES_PASSWORD` den Wert hat, mit dem die Datenbank ursprünglich angelegt wurde.

Wenn alle Stricke reißen, kannst du die PostgreSQL-Datenbank auch neu aufsetzen: Alles runterfahren (`docker compose down`), dann den Inhalt des PostgreSQL-Ordners leeren und alles neu starten. Du verlierst dann allerdings die eingestellten Strompreise und die Registrierung.

Ansonsten noch etwas zum Container-Manager von Synology: Der kennt zwar "Projekte" (das Gegenstück von `docker-compose`), kann aber keine Umgebungsvariablen verwalten. Bitte das Ding weglassen, nichts damit machen, nur auf der Kommandozeile arbeiten, also über einen SSH-Login.

**Comment by GerhardPg** [comment]
Hallo Georg, danke! Jetzt läuft's wieder. Die Stricke sind zwar gerissen, aber der Aufwand, den PostgreSQL-Ordner zu leeren und die Strompreise neu einzugeben bzw. die Registrierung zu erneuern, war dann für das Ergebnis erträglich. Alleine wäre ich da aber sicher nicht drauf gekommen. 
Vielen Dank für deinen schnellen und umfassenden Support.
Einen schönen Abend noch und immer viel Sonne aufs Dach! 
Gerhard
