### ISSUE TITLE
[FR] Add additional parameters to forecast.solar query

### ISSUE THREAD

**Issue by unclej84** [solectrus/forecast-collector#326]
Hello,

it would be nice to specify some additional parameters for the Forecast.solar query:

- inverter: in order to include additional balcony power plants (BKK) to the whole system (use case: e.g. panels have 1.2kWp but inverter limits to 0.86kWp)
- [horizon](https://doc.forecast.solar/horizon): in case you have higher buildings or trees around the location, this could be considered with comma separates list
- [actual](https://doc.forecast.solar/actual) (not sure if this is possible, only with API key): provide actual production until now in order to adjust the forecast (parameter should only be used beyond a certain time as it might influence the forecast too much when send to early - see forecast.solar doc)

**Comment by unclej84** [comment]
Wow, that was really fast - thanks a lot. Seems to work - tried with 36 horizon values as the constellation is quite strange with huge trees and housing blocks.
Already thought that `actual` parameter would not be possible - also due to the fact that there is no information on single strains of the system - only total power.
I also had a look at it but it only supports 2 sites/orientations for home pv (not sure what a paid solution with up to 4 would cost).
Can be closed then, if you want.

**Comment by ledermann** [comment]
Great, thanks for your feedback 👍
