### ISSUE TITLE
Still using old forecast collector

### ISSUE THREAD

**Issue by reimuell** [solectrus/forecast-collector#342]
Hello, 
when I enter the new lines of configuration to use the new forecast collector and comment the old configuration lines in the. env file I can see in the log files that solectrus still tries to use old forecast provider. Of course this fails now because of missing configuration statements. I believe I miss a step to use this new forecast provider. 
thx

**Comment by ledermann** [comment]
Please make sure:

1) `FORECAST_PROVIDER=solcast` is included in your `.env`
2) The new env-vars are referenced in your `docker-compose.yml` 
3) You have the latest image by `docker compose pull`
4) You have restarted your containers by `docker compose up -d`

**Comment by reimuell** [comment]
Hello,
thank you.
So the problem is obviously the yml file. I never touched this file and was
not aware that I have to include environmental variables in there.
That means I have to delete all variables starting with forecast and have
to enter all new solcast vars manually. Plus editing. env file.
May be you should write this in the readme file on github, für dummies -))
not familiar with docker.
Any yml example, link on github? I could not find any. I scanned yml file
on github but solcast vars are not included.

Danke /thx
Reiner Müller


Georg Ledermann ***@***.***> schrieb am Mi., 19. Juni 2024,
13:05:

**Comment by ledermann** [comment]
You are absolutely right, the configuration of `solcast.com` is missing in the hosting guide. I have just [added](https://github.com/solectrus/hosting/commit/3fffc57986939c8abded9879a3976f06f3d15a7b) it.

**Comment by reimuell** [comment]
Hello,
yes thx I changed my yml and. env this morning. I didn't remove old. env
entries for forecasting, it's working fine according to the log.
My problem was the API key and the recource ID, API key is a little bit
hidden, so I mixed these two items. But know it's clear.

kind regards
Reiner Müller


Georg Ledermann ***@***.***> schrieb am Do., 20. Juni 2024,
13:20:

**Comment by ledermann** [comment]
Just added support for solcast.com to the [configurator](https://configurator.solectrus.de/), so this issue can be closed.
