### ISSUE TITLE
Add support for paid plan

### ISSUE THREAD

**Issue by ledermann** [solectrus/forecast-collector#72]
Add support to use the paid plan of forecast.solar, which requires an API key:
http://doc.forecast.solar/doku.php?id=api:estimate#professional

Reference: https://github.com/jbaesner/quarkus-forecast-collector/issues/1

**Comment by ledermann** [comment]
@Bart1909 and @noffycws: I have just added support for the forecast.solar API key. 

If you want to try this out, you can use the development image `ghcr.io/solectrus/forecast-collector:develop`. Just put your API key into the ENV variable `FORECAST_SOLAR_APIKEY` (`.env` and `docker-compose.yml`)

Any feedback would be appreciated.

**Comment by noffycws** [comment]
Sorry for the delay.

I tested the function today. I added the variable to `docker-compose.yml` and `.env`. And now I have a forecast for the next 6 days (I have the professional account).

Thanks for the add on of this function.

**Comment by ledermann** [comment]
Thanks for your feedback, @noffycws. I will publish a new release soon.

**Comment by gereons** [comment]
Tagging on to this: do you also plan to support multi-plane requests for e.g. east-west orientations? The "personal plus" paid plan supports this via the `https://api.forecast.solar/:apikey/estimate/:lat/:lon/:dec1/:az1/:kwp1/:dec2/:az2/:kwp2` URL format.

**Comment by ledermann** [comment]
Released as [v0.3.0](https://github.com/solectrus/forecast-collector/releases/tag/v0.3.0) two weeks ago.
